name: ingestion_workflow

on:
  push:
    branches:
      - yml-main-testing

jobs:
  run-tests: 
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Make
        run: sudo apt install make -y
      - name: Create Environment
        run: make requirements
      - name: Dev Setup
        run: make dev-setup
      - name: Run Tests
        run: make run-checks

